import type { FactBundle } from "../analytics/fact-bundle.js";

/**
 * A single section in a briefing draft.
 * Each section contains a title and narrative text with embedded citations.
 */
export interface BriefingSection {
  readonly id: string;
  readonly title: string;
  readonly content: string;
}

/**
 * Initial draft briefing generated by Analyst node.
 * Contains narrative sections with citations to FactBundle fields.
 */
export interface BriefingDraft {
  readonly sections: readonly BriefingSection[];
  readonly generatedAt: string;
}

/**
 * A single correction requested by Auditor node.
 * Maps a claim to the issue and the suggested fix.
 */
export interface Change {
  readonly claim: string;
  readonly issue: string;
  readonly fix: string;
}

/**
 * Audit result from Auditor node.
 * Contains approval status and list of corrections if rejected.
 */
export interface AuditResult {
  readonly approved: boolean;
  readonly corrections: readonly Change[];
  readonly checklist: {
    readonly numericalAccuracy: boolean;
    readonly noHallucinations: boolean;
    readonly logicConsistency: boolean;
    readonly citationFormat: boolean;
  };
}

/**
 * Complete state for the briefing generation workflow.
 * Tracks FactBundle, drafts, audit results, and workflow progress.
 */
export interface BriefingState {
  readonly factBundle: FactBundle;
  readonly uploadId: string;
  readonly period: string;

  // Workflow progress
  readonly analystDraft?: BriefingDraft;
  readonly auditResult?: AuditResult;
  readonly iterationCount: number; // 0, 1, 2
  readonly approved: boolean;

  // Error tracking
  readonly error?: string;
  readonly timeout?: boolean;
}

/**
 * Final approved briefing, ready for storage.
 * Contains all sections and metadata.
 */
export interface ApprovedBriefing {
  readonly sections: readonly BriefingSection[];
  readonly iterationsRequired: number;
  readonly auditApprovedAt: string;
  readonly factBundleSummary: {
    readonly period: string;
    readonly totalRevenue: number;
    readonly highRiskSkuCount: number;
    readonly recommendationCount: number;
  };
}
